export const ThemeDark = {
  title: "Dark",
  fontColor: "#ffffff",
  backgroundColor: "#161622",
  iconContainerColor: "#1E1E2D",
};

export const ThemeLight = {
  title: "Light",
  fontColor: "#000000",
  backgroundColor: "#FFFFFF",
  iconContainerColor: "#f2f2f2",
};

export const TransactionsHistoryData = [
  {
    id: 1,
    title: "Apple Store",
    category: "Entertainment",
    amount: "-$5.99",
    type: "black",
    logo: require("../assets/apple-white.png"),
  },
  {
    id: 2,
    title: "Spotify",
    category: "Music",
    amount: "-$12.99",
    type: "black",
    logo: require("../assets/spotify.png"),
  },
  {
    id: 3,
    title: "Money Transfer",
    category: "Transaction",
    amount: "$300",
    type: "blue",
    logo: require("../assets/moneyTransfer.png"),
  },
  {
    id: 4,
    title: "Grocery",
    category: "Food & Drink",
    amount: "-$88",
    type: "black",
    logo: require("../assets/grocery.png"),
  },
  {
    id: 5,
    title: "Beverage",
    category: "Food & Drink",
    amount: "-$22.50",
    type: "black",
    logo: require("../assets/apple.png"),
  },
  {
    id: 6,
    title: "Jeans",
    category: "Shopping",
    amount: "-$21.00",
    type: "black",
    logo: require("../assets/apple.png"),
  },
  {
    id: 7,
    title: "Yango",
    category: "Transport",
    amount: "-$12.50",
    type: "black",
    logo: require("../assets/apple.png"),
  },
  {
    id: 9,
    title: "Tips",
    category: "Income",
    amount: "+$2000.00",
    type: "blue",
    logo: require("../assets/apple.png"),
  },
];

export const TransactionsHistoryDataDark = [
  {
    id: 1,
    title: "Apple Store",
    category: "Entertainment",
    amount: "-$5.99",
    type: "black",
    logo: require("../assets/apple.png"),
  },
  {
    id: 2,
    title: "Spotify",
    category: "Music",
    amount: "-$12.99",
    type: "black",
    logo: require("../assets/spotify.png"),
  },
  {
    id: 3,
    title: "Money Transfer",
    category: "Transaction",
    amount: "$300",
    type: "blue",
    logo: require("../assets/moneyTransfer.png"),
  },
  {
    id: 4,
    title: "Grocery",
    category: "Food & Drink",
    amount: "-$88",
    type: "black",
    logo: require("../assets/grocery.png"),
  },
  {
    id: 5,
    title: "Beverage",
    category: "Food & Drink",
    amount: "-$22.50",
    type: "black",
    logo: require("../assets/apple.png"),
  },
  {
    id: 6,
    title: "Jeans",
    category: "Shopping",
    amount: "-$21.00",
    type: "black",
    logo: require("../assets/apple.png"),
  },
  {
    id: 7,
    title: "Yango",
    category: "Transport",
    amount: "-$12.50",
    type: "black",
    logo: require("../assets/apple.png"),
  },
  {
    id: 9,
    title: "Tips",
    category: "Income",
    amount: "+$2000.00",
    type: "blue",
    logo: require("../assets/apple.png"),
  },
];
